apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  app.kubernetes.io/part-of: vaultrix-dr
  environment: primary
images:
  - name: notes-app
    newName: 598120810297.dkr.ecr.ap-south-1.amazonaws.com/vaultrix-dr-notes
    newTag: replace-me
