apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  app.kubernetes.io/part-of: vaultrix-dr
  environment: primary
images:
  - name: notes-app
    newName: ghcr.io/elzabeth-l/vaultrix-eks-notes
    newTag: replace-me
