apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  app.kubernetes.io/part-of: vaultrix-dr
  environment: dr
images:
  - name: notes-app
    newName: ghcr.io/elzabeth-l/vaultrix-eks-notes
    newTag: replace-me
patches:
  - target:
      kind: Ingress
      name: notes
    patch: |-
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1load-balancer-attributes
        value: deletion_protection.enabled=false
      - op: remove
        path: /spec/rules/0/host
